# Setup
title:        Biosynthesis of natural products
tagline:      Tutorials for the fungal project
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Sebastian Theobald
  url:        seth-1.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
